windows: 
  - name: bxm-automation
    root: ~/bauer/@bxm/automation
    layout: main-vertical-flipped
    panes:
      - profile git bxm-automation && clear
      - profile npm bxm-automation && clear && cd src